import type { IDecision, Feedback } from "@merlynn/db";
import { User } from "@merlynn/db";
import { hash } from "bcryptjs";

function daysAgo(n: number): Date {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(Math.floor(Math.random() * 14) + 7, Math.floor(Math.random() * 60));
  return d;
}

export async function seedUsers(): Promise<void> {
  const existingUser = await User.findOne({ email: "admin@merlynn.co.za" });
  if (!existingUser) {
    const passwordHash = await hash("demo1234", 12);
    await User.create({
      email: "admin@merlynn.co.za",
      name: "Sarah Ndlovu",
      passwordHash,
      role: "ADMIN",
    });
  }
}

export const seedDecisions: IDecision[] = [
  {
    transactionId: "TXN-2026-0301",
    amount: 2450000,
    supplierName: "Meridian Global Trading Ltd",
    country: "Nigeria",
    transactionType: "PAYMENT",
    riskLevel: "HIGH",
    riskScore: 94,
    confidence: 89,
    modelName: "Fraud Analyst — Carl",
    explanation:
      "Unusually large payment to a newly onboarded supplier in a high-risk jurisdiction. Transaction amount exceeds the 99th percentile for this supplier category. No prior trading history detected.",
    shapValues: [
      { factor: "jurisdiction_risk", contribution: 0.32 },
      { factor: "amount_anomaly", contribution: 0.28 },
      { factor: "supplier_tenure", contribution: 0.21 },
      { factor: "transaction_velocity", contribution: 0.12 },
      { factor: "industry_pattern", contribution: 0.07 },
    ],
    outcome: "FLAGGED",
    reviewedBy: "s.ndlovu@merlynn.co.za",
    feedback: {
      rating: "CORRECT",
      note: "Confirmed fraudulent supplier. Account frozen.",
      submittedBy: "s.ndlovu@merlynn.co.za",
      submittedAt: daysAgo(0),
    } as Feedback,
    timestamp: daysAgo(0),
  },
  {
    transactionId: "TXN-2026-0302",
    amount: 89500,
    supplierName: "Huawei Technologies SA",
    country: "South Africa",
    transactionType: "PROCUREMENT",
    riskLevel: "LOW",
    riskScore: 15,
    confidence: 93,
    modelName: "Fraud Analyst — Carl",
    explanation:
      "Standard procurement from established technology supplier. Amount within historical norms. Supplier has 8+ years of verified trade history.",
    shapValues: [
      { factor: "supplier_tenure", contribution: -0.35 },
      { factor: "amount_anomaly", contribution: -0.22 },
      { factor: "jurisdiction_risk", contribution: -0.18 },
      { factor: "transaction_velocity", contribution: 0.05 },
    ],
    outcome: "PASSED",
    timestamp: daysAgo(0),
  },
  {
    transactionId: "TXN-2026-0303",
    amount: 567000,
    supplierName: "Caspian Freight Solutions",
    country: "Kazakhstan",
    transactionType: "INVOICE",
    riskLevel: "HIGH",
    riskScore: 87,
    confidence: 84,
    modelName: "Fraud Analyst — Carl",
    explanation:
      "Invoice from a logistics company in Central Asia with inconsistent documentation. Amount significantly higher than previous invoices from this corridor. Pattern matches known trade-based money laundering typology.",
    shapValues: [
      { factor: "document_consistency", contribution: 0.29 },
      { factor: "jurisdiction_risk", contribution: 0.26 },
      { factor: "amount_anomaly", contribution: 0.22 },
      { factor: "corridor_pattern", contribution: 0.15 },
      { factor: "beneficiary_structure", contribution: 0.08 },
    ],
    outcome: "FLAGGED",
    reviewedBy: "m.patel@merlynn.co.za",
    feedback: {
      rating: "PARTIAL",
      note: "Supplier is legitimate but documentation was genuinely incomplete. Flagging was overly aggressive.",
      submittedBy: "m.patel@merlynn.co.za",
      submittedAt: daysAgo(0),
    } as Feedback,
    timestamp: daysAgo(0),
  },
  {
    transactionId: "TXN-2026-0304",
    amount: 34200,
    supplierName: "Woolworths Holdings",
    country: "South Africa",
    transactionType: "PAYMENT",
    riskLevel: "LOW",
    riskScore: 8,
    confidence: 97,
    modelName: "Fraud Analyst — Carl",
    explanation:
      "Routine payment to a JSE-listed retail corporation. Transaction aligns with established payment schedule and historical amounts.",
    shapValues: [
      { factor: "supplier_tenure", contribution: -0.4 },
      { factor: "listing_status", contribution: -0.3 },
      { factor: "amount_anomaly", contribution: -0.15 },
      { factor: "schedule_adherence", contribution: -0.1 },
    ],
    outcome: "PASSED",
    timestamp: daysAgo(0),
  },
  {
    transactionId: "TXN-2026-0305",
    amount: 178000,
    supplierName: "Zhangjiagang Bonded Logistics",
    country: "China",
    transactionType: "TRANSFER",
    riskLevel: "MEDIUM",
    riskScore: 52,
    confidence: 71,
    modelName: "Fraud Analyst — Carl",
    explanation:
      "Cross-border transfer to Chinese logistics company. Amount is within normal range but transfer routing includes an intermediary in Hong Kong not previously seen.",
    shapValues: [
      { factor: "routing_complexity", contribution: 0.25 },
      { factor: "jurisdiction_risk", contribution: 0.15 },
      { factor: "amount_anomaly", contribution: -0.08 },
      { factor: "supplier_tenure", contribution: -0.12 },
      { factor: "intermediary_novelty", contribution: 0.2 },
    ],
    outcome: "REVIEWING",
    timestamp: daysAgo(0),
  },
  {
    transactionId: "TXN-2026-0306",
    amount: 1230000,
    supplierName: "Dubrovnik Maritime Services",
    country: "Croatia",
    transactionType: "PAYMENT",
    riskLevel: "MEDIUM",
    riskScore: 61,
    confidence: 74,
    modelName: "Fraud Analyst — Carl",
    explanation:
      "Large maritime services payment to Croatian company. While the jurisdiction is EU, the amount represents a 340% increase over the previous quarter's average for this supplier.",
    shapValues: [
      { factor: "amount_anomaly", contribution: 0.35 },
      { factor: "supplier_trend", contribution: 0.2 },
      { factor: "jurisdiction_risk", contribution: -0.1 },
      { factor: "industry_norm", contribution: 0.08 },
    ],
    outcome: "REVIEWING",
    reviewedBy: "j.botha@merlynn.co.za",
    feedback: {
      rating: "CORRECT",
      note: "Amount spike was due to a new contract. Reviewing was appropriate given the anomaly.",
      submittedBy: "j.botha@merlynn.co.za",
      submittedAt: daysAgo(1),
    } as Feedback,
    timestamp: daysAgo(1),
  },
  {
    transactionId: "TXN-2026-0307",
    amount: 4890000,
    supplierName: "Caracas Energy Holdings",
    country: "Venezuela",
    transactionType: "PROCUREMENT",
    riskLevel: "HIGH",
    riskScore: 96,
    confidence: 93,
    modelName: "Fraud Analyst — Carl",
    explanation:
      "Extremely high-value procurement from sanctioned-adjacent jurisdiction. Venezuela subject to multiple international sanctions programs. Supplier entity structure includes BVI-registered holding company.",
    shapValues: [
      { factor: "sanctions_proximity", contribution: 0.38 },
      { factor: "jurisdiction_risk", contribution: 0.25 },
      { factor: "amount_anomaly", contribution: 0.18 },
      { factor: "entity_structure", contribution: 0.12 },
      { factor: "beneficial_ownership", contribution: 0.07 },
    ],
    outcome: "FLAGGED",
    reviewedBy: "s.ndlovu@merlynn.co.za",
    timestamp: daysAgo(1),
  },
  {
    transactionId: "TXN-2026-0308",
    amount: 67800,
    supplierName: "Siemens Africa",
    country: "Germany",
    transactionType: "INVOICE",
    riskLevel: "LOW",
    riskScore: 5,
    confidence: 95,
    modelName: "Fraud Analyst — Carl",
    explanation:
      "Standard invoice from Siemens subsidiary. Fully compliant documentation. Transaction matches purchase order and delivery confirmation.",
    shapValues: [
      { factor: "supplier_reputation", contribution: -0.42 },
      { factor: "document_completeness", contribution: -0.28 },
      { factor: "jurisdiction_risk", contribution: -0.2 },
    ],
    outcome: "PASSED",
    feedback: {
      rating: "INCORRECT",
      note: "Invoice amount was later found to include unapproved surcharges. Should have been flagged for review.",
      submittedBy: "m.patel@merlynn.co.za",
      submittedAt: daysAgo(1),
    } as Feedback,
    timestamp: daysAgo(1),
  },
  {
    transactionId: "TXN-2026-0309",
    amount: 345000,
    supplierName: "Al-Rashid Trading Company",
    country: "UAE",
    transactionType: "TRANSFER",
    riskLevel: "MEDIUM",
    riskScore: 58,
    confidence: 69,
    modelName: "Fraud Analyst — Carl",
    explanation:
      "Transfer to Dubai-based trading company. UAE is a known transit hub. Amount is within norms but company was recently re-registered under new ownership.",
    shapValues: [
      { factor: "ownership_change", contribution: 0.28 },
      { factor: "jurisdiction_risk", contribution: 0.18 },
      { factor: "amount_anomaly", contribution: -0.05 },
      { factor: "transit_hub_flag", contribution: 0.15 },
    ],
    outcome: "REVIEWING",
    timestamp: daysAgo(1),
  },
  {
    transactionId: "TXN-2026-0310",
    amount: 23400,
    supplierName: "Cape Union Mart",
    country: "South Africa",
    transactionType: "PAYMENT",
    riskLevel: "LOW",
    riskScore: 3,
    confidence: 96,
    modelName: "Fraud Analyst — Carl",
    explanation:
      "Small retail payment to well-known South African retailer. Completely within normal operating parameters.",
    shapValues: [
      { factor: "supplier_tenure", contribution: -0.38 },
      { factor: "amount_anomaly", contribution: -0.35 },
      { factor: "jurisdiction_risk", contribution: -0.22 },
    ],
    outcome: "PASSED",
    timestamp: daysAgo(1),
  },
  {
    transactionId: "TXN-2026-0311",
    amount: 890000,
    supplierName: "Minsk Industrial Components",
    country: "Belarus",
    transactionType: "PROCUREMENT",
    riskLevel: "HIGH",
    riskScore: 91,
    confidence: 88,
    modelName: "Fraud Analyst — Carl",
    explanation:
      "Procurement from Belarusian industrial supplier. Belarus subject to EU and US sanctions. Transaction pattern consistent with sanctions circumvention through third-country routing.",
    shapValues: [
      { factor: "sanctions_exposure", contribution: 0.36 },
      { factor: "routing_pattern", contribution: 0.24 },
      { factor: "jurisdiction_risk", contribution: 0.2 },
      { factor: "amount_anomaly", contribution: 0.11 },
    ],
    outcome: "FLAGGED",
    reviewedBy: "m.patel@merlynn.co.za",
    feedback: {
      rating: "CORRECT",
      note: "Sanctions violation confirmed. Reported to regulatory authority.",
      submittedBy: "s.ndlovu@merlynn.co.za",
      submittedAt: daysAgo(2),
    } as Feedback,
    timestamp: daysAgo(2),
  },
  {
    transactionId: "TXN-2026-0312",
    amount: 156000,
    supplierName: "Santos Brasil Participacoes",
    country: "Brazil",
    transactionType: "PAYMENT",
    riskLevel: "MEDIUM",
    riskScore: 45,
    confidence: 72,
    modelName: "Fraud Analyst — Carl",
    explanation:
      "Payment to Brazilian port services company. Medium-risk jurisdiction. Amount is slightly elevated but supplier has 3 years of history. Monitoring recommended.",
    shapValues: [
      { factor: "jurisdiction_risk", contribution: 0.18 },
      { factor: "amount_anomaly", contribution: 0.12 },
      { factor: "supplier_tenure", contribution: -0.15 },
      { factor: "port_services_flag", contribution: 0.1 },
    ],
    outcome: "PASSED",
    timestamp: daysAgo(2),
  },
  {
    transactionId: "TXN-2026-0313",
    amount: 2100000,
    supplierName: "Myanmar Jade Resources",
    country: "Myanmar",
    transactionType: "TRANSFER",
    riskLevel: "HIGH",
    riskScore: 98,
    confidence: 96,
    modelName: "Fraud Analyst — Carl",
    explanation:
      "Very high-value transfer to Myanmar-based resource company. Myanmar under comprehensive sanctions by multiple jurisdictions. Jade trade linked to military funding. Immediate escalation required.",
    shapValues: [
      { factor: "sanctions_comprehensive", contribution: 0.4 },
      { factor: "sector_risk", contribution: 0.25 },
      { factor: "jurisdiction_risk", contribution: 0.2 },
      { factor: "amount_anomaly", contribution: 0.1 },
      { factor: "military_nexus", contribution: 0.05 },
    ],
    outcome: "FLAGGED",
    reviewedBy: "s.ndlovu@merlynn.co.za",
    timestamp: daysAgo(2),
  },
  {
    transactionId: "TXN-2026-0314",
    amount: 45600,
    supplierName: "Naspers Limited",
    country: "South Africa",
    transactionType: "INVOICE",
    riskLevel: "LOW",
    riskScore: 7,
    confidence: 91,
    modelName: "Fraud Analyst — Carl",
    explanation:
      "Invoice from JSE-listed media conglomerate. Established supplier with clean compliance history.",
    shapValues: [
      { factor: "listing_status", contribution: -0.38 },
      { factor: "supplier_tenure", contribution: -0.32 },
      { factor: "jurisdiction_risk", contribution: -0.18 },
    ],
    outcome: "PASSED",
    timestamp: daysAgo(2),
  },
  {
    transactionId: "TXN-2026-0315",
    amount: 723000,
    supplierName: "Istanbul Commodities Exchange",
    country: "Turkey",
    transactionType: "PAYMENT",
    riskLevel: "MEDIUM",
    riskScore: 55,
    confidence: 68,
    modelName: "Fraud Analyst — Carl",
    explanation:
      "Commodities payment routed through Istanbul. Turkey flagged as potential sanctions evasion corridor. Transaction amount within historical range but timing coincides with increased monitoring alerts.",
    shapValues: [
      { factor: "corridor_alert", contribution: 0.22 },
      { factor: "jurisdiction_risk", contribution: 0.18 },
      { factor: "timing_anomaly", contribution: 0.15 },
      { factor: "amount_anomaly", contribution: -0.05 },
    ],
    outcome: "REVIEWING",
    feedback: {
      rating: "PARTIAL",
      note: "Timing was coincidental but corridor risk assessment was valid. Supplier cleared after enhanced due diligence.",
      submittedBy: "j.botha@merlynn.co.za",
      submittedAt: daysAgo(3),
    } as Feedback,
    timestamp: daysAgo(3),
  },
  {
    transactionId: "TXN-2026-0316",
    amount: 12500,
    supplierName: "Discovery Health",
    country: "South Africa",
    transactionType: "PAYMENT",
    riskLevel: "LOW",
    riskScore: 2,
    confidence: 94,
    modelName: "Fraud Analyst — Carl",
    explanation:
      "Routine health insurance payment. Low amount to regulated financial services entity.",
    shapValues: [
      { factor: "regulated_entity", contribution: -0.45 },
      { factor: "amount_anomaly", contribution: -0.35 },
      { factor: "payment_regularity", contribution: -0.15 },
    ],
    outcome: "PASSED",
    timestamp: daysAgo(3),
  },
  {
    transactionId: "TXN-2026-0317",
    amount: 1890000,
    supplierName: "Luanda Port Authority",
    country: "Angola",
    transactionType: "PROCUREMENT",
    riskLevel: "HIGH",
    riskScore: 82,
    confidence: 82,
    modelName: "Fraud Analyst — Carl",
    explanation:
      "Large procurement payment to Angolan state-owned port entity. PEP exposure through government ownership. Angola scores high on corruption indices. Dual-use goods classification flagged.",
    shapValues: [
      { factor: "pep_exposure", contribution: 0.3 },
      { factor: "corruption_index", contribution: 0.22 },
      { factor: "amount_anomaly", contribution: 0.15 },
      { factor: "dual_use_goods", contribution: 0.12 },
      { factor: "state_ownership", contribution: 0.08 },
    ],
    outcome: "REVIEWING",
    reviewedBy: "j.botha@merlynn.co.za",
    timestamp: daysAgo(3),
  },
  {
    transactionId: "TXN-2026-0318",
    amount: 98700,
    supplierName: "Shoprite Holdings",
    country: "South Africa",
    transactionType: "PAYMENT",
    riskLevel: "LOW",
    riskScore: 6,
    confidence: 92,
    modelName: "Fraud Analyst — Carl",
    explanation:
      "Standard procurement payment to major JSE-listed retailer. All documentation complete and verified.",
    shapValues: [
      { factor: "supplier_reputation", contribution: -0.4 },
      { factor: "listing_status", contribution: -0.3 },
      { factor: "amount_anomaly", contribution: -0.2 },
    ],
    outcome: "PASSED",
    timestamp: daysAgo(3),
  },
  {
    transactionId: "TXN-2026-0319",
    amount: 456000,
    supplierName: "Dhaka Textile Consortium",
    country: "Bangladesh",
    transactionType: "INVOICE",
    riskLevel: "MEDIUM",
    riskScore: 48,
    confidence: 76,
    modelName: "Fraud Analyst — Carl",
    explanation:
      "Textile import invoice from Bangladesh. While the garment industry has known labor compliance risks, this supplier has passed recent audits. Amount is within expected range.",
    shapValues: [
      { factor: "industry_compliance_risk", contribution: 0.2 },
      { factor: "jurisdiction_risk", contribution: 0.15 },
      { factor: "audit_status", contribution: -0.18 },
      { factor: "amount_anomaly", contribution: -0.05 },
    ],
    outcome: "PASSED",
    feedback: {
      rating: "INCORRECT",
      note: "Subsequent audit revealed labor violations at this supplier. Should have been flagged for deeper review.",
      submittedBy: "s.ndlovu@merlynn.co.za",
      submittedAt: daysAgo(3),
    } as Feedback,
    timestamp: daysAgo(4),
  },
  {
    transactionId: "TXN-2026-0320",
    amount: 3200000,
    supplierName: "Gazprombank International",
    country: "Russia",
    transactionType: "TRANSFER",
    riskLevel: "HIGH",
    riskScore: 99,
    confidence: 95,
    modelName: "Cyber Risk",
    explanation:
      "Transfer to Russian state-adjacent banking entity. Gazprombank subject to targeted sanctions. Transaction blocked pending compliance review. Automatic STR filing initiated.",
    shapValues: [
      { factor: "sanctions_direct", contribution: 0.45 },
      { factor: "entity_designation", contribution: 0.25 },
      { factor: "jurisdiction_risk", contribution: 0.18 },
      { factor: "amount_anomaly", contribution: 0.08 },
      { factor: "state_nexus", contribution: 0.04 },
    ],
    outcome: "FLAGGED",
    reviewedBy: "s.ndlovu@merlynn.co.za",
    feedback: {
      rating: "CORRECT",
      note: "Sanctions hit confirmed. STR filed and transaction permanently blocked.",
      submittedBy: "s.ndlovu@merlynn.co.za",
      submittedAt: daysAgo(4),
    } as Feedback,
    timestamp: daysAgo(4),
  },
  {
    transactionId: "TXN-2026-0321",
    amount: 234000,
    supplierName: "Maputo Shipping & Logistics",
    country: "Mozambique",
    transactionType: "PAYMENT",
    riskLevel: "MEDIUM",
    riskScore: 63,
    confidence: 73,
    modelName: "Fraud Analyst — Carl",
    explanation:
      "Payment to Mozambican logistics company. Elevated risk due to ongoing insurgency in northern regions and associated financial crime concerns. Supplier based in Maputo (lower risk area).",
    shapValues: [
      { factor: "regional_conflict", contribution: 0.22 },
      { factor: "jurisdiction_risk", contribution: 0.2 },
      { factor: "supplier_location", contribution: -0.1 },
      { factor: "amount_anomaly", contribution: 0.08 },
    ],
    outcome: "REVIEWING",
    timestamp: daysAgo(4),
  },
  {
    transactionId: "TXN-2026-0322",
    amount: 15800,
    supplierName: "FNB Corporate",
    country: "South Africa",
    transactionType: "TRANSFER",
    riskLevel: "LOW",
    riskScore: 4,
    confidence: 88,
    modelName: "Fraud Analyst — Carl",
    explanation:
      "Internal corporate banking transfer. FNB is a regulated South African bank. Routine treasury operation.",
    shapValues: [
      { factor: "regulated_entity", contribution: -0.42 },
      { factor: "domestic_transfer", contribution: -0.3 },
      { factor: "amount_anomaly", contribution: -0.22 },
    ],
    outcome: "PASSED",
    timestamp: daysAgo(5),
  },
  {
    transactionId: "TXN-2026-0323",
    amount: 567000,
    supplierName: "Karachi Steel Mills",
    country: "Pakistan",
    transactionType: "PROCUREMENT",
    riskLevel: "MEDIUM",
    riskScore: 51,
    confidence: 77,
    modelName: "Fraud Analyst — Carl",
    explanation:
      "Steel procurement from Pakistani supplier. Moderate jurisdiction risk. Steel products require end-use monitoring due to dual-use potential. Supplier has mixed compliance history.",
    shapValues: [
      { factor: "dual_use_monitoring", contribution: 0.22 },
      { factor: "jurisdiction_risk", contribution: 0.18 },
      { factor: "compliance_history", contribution: 0.12 },
      { factor: "amount_anomaly", contribution: -0.05 },
    ],
    outcome: "PASSED",
    timestamp: daysAgo(5),
  },
  {
    transactionId: "TXN-2026-0324",
    amount: 1450000,
    supplierName: "Pyongyang Trading Corp",
    country: "North Korea",
    transactionType: "PAYMENT",
    riskLevel: "HIGH",
    riskScore: 100,
    confidence: 92,
    modelName: "Cyber Risk",
    explanation:
      "CRITICAL: Payment attempt to DPRK-based entity. North Korea subject to comprehensive UN, US, and EU sanctions. Transaction automatically blocked. Compliance officer and regulators notified immediately.",
    shapValues: [
      { factor: "sanctions_comprehensive", contribution: 0.5 },
      { factor: "jurisdiction_risk", contribution: 0.3 },
      { factor: "entity_screening", contribution: 0.15 },
      { factor: "amount_anomaly", contribution: 0.05 },
    ],
    outcome: "FLAGGED",
    reviewedBy: "s.ndlovu@merlynn.co.za",
    timestamp: daysAgo(5),
  },
  {
    transactionId: "TXN-2026-0325",
    amount: 78900,
    supplierName: "Vodacom Business",
    country: "South Africa",
    transactionType: "INVOICE",
    riskLevel: "LOW",
    riskScore: 9,
    confidence: 90,
    modelName: "Fraud Analyst — Carl",
    explanation:
      "Telecommunications services invoice from major listed SA provider. Regular monthly billing within expected parameters.",
    shapValues: [
      { factor: "supplier_reputation", contribution: -0.38 },
      { factor: "billing_regularity", contribution: -0.3 },
      { factor: "amount_anomaly", contribution: -0.2 },
    ],
    outcome: "PASSED",
    timestamp: daysAgo(5),
  },
];
